version: "3.8"

networks:
  eCampusNetwork:
    driver: bridge

services:
  postgres-app:
    image: postgres:latest
    networks:
      - eCampusNetwork
    restart: always
    container_name: postgres-container
    environment:
      POSTGRES_DB: eCampusDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      #       - ./postgres-data:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  modulmanager-app:
    image: modulmanager
    restart: no
    container_name: modulmanager-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres-app # waits for db to run
    networks:
      - eCampusNetwork