apiVersion: v1
kind: Service
metadata:
  name: studentmanager-service
spec:
  type: LoadBalancer
  selector:
    app: studentmanager
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082